---
- hosts: localhost
  gather_facts: false

  vars:
    image_name: hello-go
    image_tag: latest
    registry_url: localhost:5000

  tasks:
    - name: Build the {{ image_name }} Image
      docker_image:
        build:
          path: ../hello-go
          pull: false
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Run the {{ image_name }} Image
      docker_container:
        name: "{{ image_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        published_ports:
          - 8180:8180

    - name: Verify {{ image_name }} is responding
      uri:
        url: http://localhost:8180/test
        return_content: true
      register: container_response
      failed_when: "'/test' not in container_response.content"

    - name: Stop and remove the {{ image_name }} container
      docker_container:
        name: "{{ image_name }}"
        state: absent

  post_tasks:
    - name: Log into Docker registry
      docker_login:
        registry: "{{ registry_url }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
      when:
        - registry_url is defined and registry_url != ''
        - registry_username is defined and registry_username != ''
        - registry_password is defined and registry_password != ''

    - name: Push Image to Docker registry
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        repository: "{{ registry_url }}/{{ image_name }}:{{ image_tag }}"
        push: true
        source: local

