---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current date
      command: date
      register: current_date
      changed_when: false
    - name: Print current date
      debug:
        msg: "{{ current_date.stdout }}"
